require: rubocop-rails

Rails:
  Enabled: true

Rails/ActionFilter:
  Enabled: false

Rails/Delegate:
  Enabled: false


Rails/FilePath:
  Enabled: false

Rails/Output:
  Enabled: true
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb
    - spec/**/*.rb

Rails/SkipsModelValidations:
  Enabled: false

Rails/RequestReferer:
  EnforcedStyle: referrer

Rails/DynamicFindBy:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false
